exports.buildUrl = require('./lib/buildUrl')
exports.BrowserEvents = require('./lib/BrowserEvents')
exports.castToArray = require('./lib/castToArray')
exports.castObjectAsArray = require('./lib/castObjectAsArray')
exports.copyObject = require('./lib/copyObject')
exports.errors = require('./lib/errors')
exports.getClassName = require('./lib/getClassName')
exports.getRandomString = require('./lib/getRandomString')
exports.getPath = require('./lib/getPath')
exports.getValue = require('./lib/getValue')
exports.httpBuildQuery = require('./lib/httpBuildQuery')
exports.intersection = require('./lib/intersection')
exports.isEqual = require('./lib/isEqual')
exports.isInstance = require('./lib/isInstance')
exports.isObject = require('./lib/isObject')
exports.merge = require('./lib/merge')
exports.modifyUrl = require('./lib/modifyUrl')
exports.parseQueryString = require('./lib/parseQueryString')
exports.removeFromArray = require('./lib/removeFromArray')
exports.serializer = require('./lib/serializer')
exports.setValue = require('./lib/setValue')
exports.sleep = require('./lib/sleep')
exports.splitStringIntoChunks = require('./lib/splitStringIntoChunks')
exports.strPad = require('./lib/strPad')
exports.trim = require('./lib/trim')
exports.typecastString = require('./lib/typecastString')
exports.unique = require('./lib/unique')
exports.urlName = require('./lib/urlName')

// Determine the type of config provided
exports.Config = require('./lib/Config')

exports.Localization = require('./lib/Localization')
